### ISSUE TITLE
When I use the coord_polar function to roll up the x axis, the coordinates will be positioned incorrectly

### ISSUE THREAD

**Issue by yuanzhoulvpi2017** [MattCowgill/ggannotate#18]
When I use the coord_polar function to roll up the x axis, the coordinates will be positioned incorrectly
![image](https://user-images.githubusercontent.com/30610553/76855684-9bfd4b80-688c-11ea-8f63-97400fe1a032.png)

**Comment by MattCowgill** [comment]
Thanks @yuanzhoulvpi2017 for filing the issue. That is a tricky one. I will see if I can figure out a way to fix this. It may take me some time, I'm sorry.

**Comment by MattCowgill** [comment]
Hi, I don't think this is possible to fix, sorry.
