### ISSUE TITLE
Allow users to add a type of reference line to show a % difference in each bar  

### ISSUE THREAD

**Issue by bongho** [MattCowgill/ggannotate#19]
Dear,

To draw something like the below, I have been using Thinkcell,  a Microsoft Office plugin, after cleansing the data in R.

I hope ggannotate library would allow a user to add the reference line to show a % difference like the below.

Thanks.

![Reference Line](https://i.imgur.com/aGs6TZk.png)

**Comment by MattCowgill** [comment]
Hi, thanks for filing an issue. I'm unclear about which aspect of this plot you want to be able to add using `ggannotate`. Could you please clarify? Thanks

**Comment by bongho** [comment]
I gave the highlight on what I want to add using the package in the image as below:

[Imgur](https://imgur.com/p6xnoee)

**Comment by MattCowgill** [comment]
Hi @bongho thanks again for filing an issue, but I don't think `ggannotate` is well-suited to the task you have in mind. `ggannotate` is a tool to help you place ggplot2 geoms - like labels, or curves - on plots. As far as I know there is no ggplot2 geom that corresponds to what you have in mind, so `ggannotate` is no help.
