### ISSUE TITLE
Enable ggannotate when using ggplot2 + tidiverse pipe (%>%)

### ISSUE THREAD

**Issue by camilogarciabotero** [MattCowgill/ggannotate#21]
HI @MattCowgill,

First of all, `ggannotate` is such a great idea and I hope you can develop it further! 
So, I was trying to draw some lines in a ggplot2 plot that included some data cleaning and wrapping with the `tidiverse` package. Once I tried to open `ggannotate` it pops out the following error:

> Error in all_sorted %>% select(scaffold, taxonomy) %>% ggplot(aes(fill = taxonomy,  : 
  could not find function "%>%"

If have some idea of how can I sort this out it would be great,
Cheers.

**Comment by camilogarciabotero** [comment]
Apparently when the plot is created as a variable, and the you use `ggannotate(variable)` then it computes the annotation quite good!

**Comment by MattCowgill** [comment]
Thanks @camilogarciabotero. I’m glad you got it sorted. When it was failing for you, were you using the RStudio plugin? (The drop down menu)

**Comment by camilogarciabotero** [comment]
Yeap! Once I computed the `ggannotate(variable)` it opens the plain!

Thank you!
