### ISSUE TITLE
Add box annotation

### ISSUE THREAD

**Issue by jhelvy** [MattCowgill/ggannotate#30]
In addition to labels and arrows, it's sometimes helpful to also draw a box around sections of a chart. I've added this in [my simple app](https://github.com/jhelvy/gglabelr), and I'd be happy to make this addition as well. With how you've set things up for this app, I think I could make this addition pretty quickly.

**Comment by MattCowgill** [comment]
Hi @jhelvy, great, that would be excellent! Thanks

**Comment by jhelvy** [comment]
I think this is solved now with [this PR](https://github.com/MattCowgill/ggannotate/pull/32)

**Comment by jhelvy** [comment]
Woops, some tests failed...I'll try and fix them then re-submit the PR.

**Comment by jhelvy** [comment]
Okay, I think it's okay now in [this PR](https://github.com/MattCowgill/ggannotate/pull/33) - I just had to update the documentation.
