### ISSUE TITLE
Fill color in geom_rect remains in geom_label

### ISSUE THREAD

**Issue by jhelvy** [MattCowgill/ggannotate#39]
After using geom_rect, the fill color remains for the geom_label fill. Could fix this by adding a fill input for geom_label, and maybe resetting the default values when the user switches between different geoms.

**Comment by MattCowgill** [comment]
Hi @jhelvy, thanks for raising this. This will be fixed when I add the ability to simultaneously add multiple geoms, which I will do soon. My attention has been diverted by other projects.

**Comment by jhelvy** [comment]
Looking forward to it! I'm actively using the app to annotate charts, and even in its current form it's saving me lots of time searching for the precise coordinates of where to put things.

**Comment by MattCowgill** [comment]
FYI I've now added the ability to add multiple annotations. It's glitchy and not particularly fast. Will re-write soon.

**Comment by jhelvy** [comment]
Looks great! The issue about the `geom_rect` fill remaining after swapping to `geom_label` appears to be resolved.
