### ISSUE TITLE
Nothing renders in shiny

### ISSUE THREAD

**Issue by robertwwalker** [MattCowgill/ggannotate#4]
I am attaching a screen shot that should be a reprex of sorts built off of data(VonBort).  The shiny starts but the plot is deformed [I think all the plotting is in a tiny splice at the bottom].  If I click anywhere in the box, it crashes.  The error is:

Warning: Error in UseMethod: no applicable method for 'ggplot_build' applied to an object of class "function"

The box is Ubuntu 18.04LTS with an almost entirely CRAN package installation.  This package is such a great idea, anything that I can do to help I will.  Incidentally, I also tried it with

fake.data <- data.frame(x=seq(1,10), y=seq(2,11))
q <- ggplot(fake.data) + aes(x=x, y=y) + geom_point()
ggannotate:::ggannotate(q)

And get the same behavior.

![gganotate](https://user-images.githubusercontent.com/22829624/74680386-4d696e00-5175-11ea-853e-9ecc0cd31517.png)

Apologies for my bad choice of screen shot apps.  I really should look for a better one.

**Comment by MattCowgill** [comment]
Hi @robertwwalker thanks very much for filing this issue and sorry about this problem. I'll try to figure out what is causing it and fix it as soon as I can.

**Comment by MattCowgill** [comment]
Your example doesn't work for me either (on macOS). But it does work when I highlight the plot code and then invoke the Shiny app via the RStudio add-ins menu. Weird. Does that work for you? I'll try and figure out what's going on

**Comment by robertwwalker** [comment]
That solved it for both. Thanks very much.

**Comment by robertwwalker** [comment]
For what it is worth, I got to the nonworking approach from the example in the readme.md that passes a stored plot.  Has that ever worked?  I tried it on a windows machine to the same effect.  

As a friendly and immediate fix, perhaps just a slight modification to the readme.md that doesn't imply this and then a future feature?  

I played with some eval and other things to try to work around it but couldn't figure it out in the time I spent on it.  By the way, this is absolutely amazing for R learners that want to be able to create enterprise quality graphics in ggplot without having learned that much R.  In fact, between esquisse and this, I think much of the ggplotverse becomes available with almost no knowledge of the language and that is really great for R educators.  Get wins early!

**Comment by MattCowgill** [comment]
Thanks @robertwwalker! Good idea, I'll amend the README and keep working to fix this problem. Yes, the example in the README works.

**Comment by robertwwalker** [comment]
Interesting. The example in the readme.md does not work for me in exactly the same way.

**Comment by MattCowgill** [comment]
Thanks again for raising this issue @robertwwalker. I've made some changes (pushed to `dev` branch) that mean it is now working for me when I select code in RStudio, or when I wrap code in `ggannotate()`, as in `ggannotate(ggplot(fake.data) + aes(x=x, y=y) + geom_point())`, or when I create a ggplot2 object then pass that object to ggannotate (as in the example above that was not working previously).

**Comment by robertwwalker** [comment]
Thank you so much! This is a very cool tool for the classroom because it allows wins early. Love it!
