### ISSUE TITLE
error when using a new source window

### ISSUE THREAD

**Issue by wfmackey** [MattCowgill/ggannotate#9]
Hello Matthew

Love the package! Great job!!

The `ggannotate` function works as expected:

![image](https://user-images.githubusercontent.com/30094143/74703330-f345d700-5260-11ea-95b3-e68df52761f3.png)

But it errors when I use a source window in R Studio (ie I 'pop out' a window):

![image](https://user-images.githubusercontent.com/30094143/74703412-3bfd9000-5261-11ea-9129-b97b8d5df890.png)

When running the `ggannotate` add-in with code highlighted from a source window, I will get the error:

```
 ggannotate:::ggannotate()
Error in UseMethod("primary_selection") : 
  no applicable method for 'primary_selection' applied to an object of class "NULL"
```

Many thanks

**Comment by MattCowgill** [comment]
I'm unsure whether this can be fixed - it might be a limitation in the RStudio API that I use to detect the user's current selection. I'll try.

**Comment by MattCowgill** [comment]
Hiii this doesn't seem to be possible. But you can invoke `ggannotate` like this:

```
library(ggplot2)
p <- ggplot(mtcars, 
            aes(x = wt, y = mpg)) + 
  geom_point() 

ggannotate::ggannotate(p)
```
